import numpy as np

from core import Population, Individual
from core.operators import Crossover
from core.Population import Population
from core.fitness_function import FitnessFunction
from core.Representation import Representation


class LinearBGACrossover(Crossover):
    """
    Implements Linear BGA Crossover. The offsprings generated by this operator are located on the line passing through
    the parents (treated as points in the space solution).

     Algorytmy Genetyczne kompedium tom I Operator krzyżowania dla problemów numerycznych. Tomasz Gwiazda pp. 205.

    :param how_many_individuals: The number of individuals to create in the offspring.
    :param fittness_function: A function that is being optimized.
    :param precision: parameter indicating precision
    :param probability: The probability of performing the crossover operation.
    :param problem_of_maximisation: The variable indicating if in algorithm we are looking for maximum or minimum of function.
    """

    allowed_representation = [Representation.REAL]

    def __init__(self,
        how_many_individuals: int,
        fittness_function: FitnessFunction,
        precision: float,
        probability: float = 0,
        problem_of_maximisation: bool = True

    ):
        super().__init__(how_many_individuals, probability)
        self.fitness_function = fittness_function
        self.problem_of_maximisation = problem_of_maximisation
        self.precision = precision

    def _cross(self, population_parent: Population) -> Population:
        """
        :param population_parent: The population to perform the crossover operation on.
        :returns: The offspring.
        """

        while True:
            parent_1, parent_2 = np.random.choice(population_parent.population, 2, replace = False)

            if not isinstance(parent_1.chromosome, np.ndarray) or not isinstance(parent_2.chromosome, np.ndarray):
                parent_1_chromosome = np.array(parent_1.chromosome)
                parent_2_chromosome = np.array(parent_2.chromosome)
            else:
                parent_1_chromosome = parent_1.chromosome
                parent_2_chromosome = parent_2.chromosome

            if not np.array_equal(parent_1_chromosome, parent_2_chromosome):
                break

        if self.fitness_function.calculate_individual_value(parent_1) >= self.fitness_function.calculate_individual_value(parent_2):
            X = parent_1_chromosome
            Y = parent_2_chromosome
        else:
            X = parent_2_chromosome
            Y = parent_1_chromosome

        if not self.problem_of_maximisation:
            tmp = X
            X = Y
            Y = tmp

        alfa = np.random.uniform(0, 1)
        rnd = np.random.uniform(0, 1)

        domain = self.fitness_function.variable_domains[0][1] - self.fitness_function.variable_domains[0][0]
        exponent = - ( alfa * self.precision)
        difference = X - Y
        vector_norm = np.linalg.norm(difference)

        if rnd <= 0.9:
            offspring_chromosome = X - (0.5*domain * pow(2, exponent) * ((X - Y)/vector_norm))
        else:
            offspring_chromosome = X + (0.5*domain * pow(2, exponent) * ((X - Y)/vector_norm))

        return Population([Individual(offspring_chromosome)])


